const CATEGORY_LABELS={all:"le mélange complet",food:"la cuisine",objects:"les objets",places:"les lieux et voyages",nature:"les animaux et la nature",culture:"la culture et les loisirs",daily:"la vie quotidienne"};
const STORAGE_KEY="undercover_used_pairs_v3";
const $=id=>document.getElementById(id);
const screens=["homeScreen","setupScreen","passScreen","secretScreen","playScreen","recallSelectScreen","recallPassScreen","recallSecretScreen","eliminationScreen","endScreen"];
let settings={players:13,under:2,white:1,category:"all"};let game=null;let selectedPlayerId=null;let recallPlayerId=null;
const memoryStorage=new Map();
const safeStorage={
  getItem(key){try{return window.localStorage.getItem(key)}catch(e){return memoryStorage.has(key)?memoryStorage.get(key):null}},
  setItem(key,value){const v=String(value);memoryStorage.set(key,v);try{window.localStorage.setItem(key,v)}catch(e){}},
  removeItem(key){memoryStorage.delete(key);try{window.localStorage.removeItem(key)}catch(e){}}
};
function readJson(key,fallback){try{const raw=safeStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch(e){return fallback}}
function showScreen(id){screens.forEach(s=>$(s).classList.toggle("hidden",s!==id));requestAnimationFrame(()=>{try{window.scrollTo({top:0,left:0,behavior:"smooth"})}catch(e){window.scrollTo(0,0)}})}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalize(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g,"'").trim()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function pairKey(p){return [normalize(p[0]),normalize(p[1])].sort().join("|||")}
function getUsed(){try{return new Set(readJson(STORAGE_KEY,[]))}catch{return new Set()}}
function saveUsed(set){safeStorage.setItem(STORAGE_KEY,JSON.stringify([...set]))}
function currentPool(){return WORD_PAIRS.filter(p=>settings.category==="all"||p[2]===settings.category)}
function updatePoolStatus(){const pool=currentPool(),used=getUsed(),remaining=pool.filter(p=>!used.has(pairKey(p))).length;$("poolStatus").textContent=`${remaining} duo${remaining>1?"s":""} inédit${remaining>1?"s":""} restant${remaining>1?"s":""} dans ${CATEGORY_LABELS[settings.category]}.`}
function updateSettingsUI(){$("playersValue").textContent=settings.players;$("underValue").textContent=settings.under;$("whiteValue").textContent=settings.white;const civ=settings.players-settings.under-settings.white;$("balanceNotice").textContent=civ<3?"Il faut conserver au moins 3 Civils.":`Composition : ${civ} Civil${civ>1?"s":""}, ${settings.under} Undercover et ${settings.white} Mr White.`;renderNames();updatePoolStatus()}
function renderNames(){const current=[...document.querySelectorAll("#namesList input")].map(i=>i.value);const saved=readJson("undercover_names",[]);const names=current.length?current:saved;$("namesList").innerHTML="";for(let i=0;i<settings.players;i++){const row=document.createElement("div");row.className="nameRow";row.innerHTML=`<div class="numBrick">${i+1}</div><input maxlength="24" value="${escapeHtml(names[i]||"")}" placeholder="Joueur ${i+1}">`;$("namesList").appendChild(row)}}
function saveNames(){const names=[...document.querySelectorAll("#namesList input")].map((i,n)=>i.value.trim()||`Joueur ${n+1}`);safeStorage.setItem("undercover_names",JSON.stringify(names));return names}
function pickPair(){const pool=currentPool();const used=getUsed();let available=pool.filter(p=>!used.has(pairKey(p)));if(!available.length){pool.forEach(p=>used.delete(pairKey(p)));available=[...pool]}const chosen=available[Math.floor(Math.random()*available.length)];used.add(pairKey(chosen));saveUsed(used);const reverse=Math.random()<.5;return{civil:reverse?chosen[1]:chosen[0],undercover:reverse?chosen[0]:chosen[1],category:chosen[2]}}
function startNewGame(){settings.category=$("categorySelect").value;const names=saveNames(),pair=pickPair();const roles=[...Array(settings.players-settings.under-settings.white).fill("civil"),...Array(settings.under).fill("under"),...Array(settings.white).fill("white")];const shuffled=shuffle(roles);game={pair,players:names.map((name,id)=>({id,name,role:shuffled[id],alive:true})),revealOrder:shuffle([...Array(settings.players).keys()]),revealIndex:0,voteNumber:1,eliminated:null,winner:null};selectedPlayerId=null;updatePoolStatus();showPass()}
function showPass(){if(game.revealIndex>=game.revealOrder.length){beginPlay();return}const id=game.revealOrder[game.revealIndex];$("passPlayerName").textContent=game.players[id].name;$("revealProgress").style.width=`${game.revealIndex/game.revealOrder.length*100}%`;showScreen("passScreen")}
function revealSecret(){const p=game.players[game.revealOrder[game.revealIndex]];if(p.role==="white"){$("secretRole").textContent="MR WHITE";$("secretWord").textContent="AUCUN MOT";$("secretWord").classList.add("whiteWord");$("secretTip").textContent="Bluffe grâce aux indices entendus et tente de découvrir le mot des Civils."}else{$("secretRole").textContent="TON MOT";$("secretWord").textContent=p.role==="civil"?game.pair.civil:game.pair.undercover;$("secretWord").classList.remove("whiteWord");$("secretTip").textContent="Mémorise-le. Ne le prononce jamais et ne montre pas cet écran."}showScreen("secretScreen")}
function hideAndPass(){game.revealIndex++;showPass()}
function beginPlay(){const alive=game.players.filter(p=>p.alive),starter=alive[Math.floor(Math.random()*alive.length)];$("startPlayerName").textContent=starter.name;renderVoteGrid();showScreen("playScreen")}
function renderVoteGrid(){const alive=game.players.filter(p=>p.alive);$("aliveStatus").textContent=`${alive.length} en jeu`;$("roundStatus").textContent=`Vote ${game.voteNumber}`;$("voteGrid").innerHTML="";game.players.forEach(p=>{const b=document.createElement("button");b.className="playerTile"+(!p.alive?" out":"")+(selectedPlayerId===p.id?" selected":"");b.textContent=p.name;b.disabled=!p.alive;b.onclick=()=>{selectedPlayerId=p.id;renderVoteGrid();$("eliminateBtn").disabled=false};$("voteGrid").appendChild(b)})}
function openRecallSelect(){if(!game)return;recallPlayerId=null;const alive=game.players.filter(p=>p.alive);$("recallPlayerGrid").innerHTML="";alive.forEach(p=>{const b=document.createElement("button");b.className="recallPlayerTile";b.textContent=p.name;b.onclick=()=>prepareRecall(p.id);$("recallPlayerGrid").appendChild(b)});showScreen("recallSelectScreen")}
function prepareRecall(playerId){const p=game&&game.players.find(x=>x.id===playerId&&x.alive);if(!p){showScreen("playScreen");return}recallPlayerId=playerId;$("recallPlayerName").textContent=p.name;showScreen("recallPassScreen")}
function openRecallSecret(){const p=game&&game.players.find(x=>x.id===recallPlayerId&&x.alive);if(!p){showScreen("playScreen");return}hideRecallWord();showScreen("recallSecretScreen")}
function showRecallWord(){const p=game&&game.players.find(x=>x.id===recallPlayerId&&x.alive);if(!p)return;const isWhite=p.role==="white";$("recallBadge").textContent=isWhite?"MR WHITE":"TON MOT";$("recallWord").textContent=isWhite?"AUCUN MOT":(p.role==="civil"?game.pair.civil:game.pair.undercover);$("recallWord").classList.toggle("whiteWord",isWhite);$("recallWord").classList.remove("hidden");$("recallPrompt").classList.add("hidden");$("recallTip").textContent=isWhite?"Tu dois continuer à bluffer grâce aux indices entendus.":"Mémorise-le sans le prononcer et sans montrer l’écran.";$("holdRecallBtn").textContent="Relâche pour cacher"}
function hideRecallWord(){$("recallWord").classList.add("hidden");$("recallPrompt").classList.remove("hidden");$("recallPrompt").textContent="Maintiens le bouton pour afficher";$("recallBadge").textContent="RAPPEL SECRET";$("recallTip").textContent="Le mot disparaît dès que tu relâches.";$("holdRecallBtn").textContent="Maintenir pour voir mon mot"}
function finishRecall(){hideRecallWord();recallPlayerId=null;renderVoteGrid();showScreen("playScreen")}
function eliminateSelected(){if(selectedPlayerId===null)return;const p=game.players[selectedPlayerId];p.alive=false;game.eliminated=p;$("eliminatedName").textContent=p.name;const label=p.role==="civil"?"CIVIL":p.role==="under"?"UNDERCOVER":"MR WHITE";$("eliminatedRole").textContent=label;$("eliminatedRole").className=`revealRole ${p.role}`;$("eliminatedInfo").textContent=p.role==="white"?"Il n’avait aucun mot.":"Son mot reste secret jusqu’à la fin.";$("whiteGuessBox").classList.toggle("hidden",p.role!=="white");$("continueBtn").classList.toggle("hidden",p.role==="white");$("whiteGuessInput").value="";showScreen("eliminationScreen")}
function checkWhiteGuess(){const guess=normalize($("whiteGuessInput").value);if(!guess){$("whiteGuessInput").classList.add("shake");setTimeout(()=>$("whiteGuessInput").classList.remove("shake"),400);return}if(guess===normalize(game.pair.civil)){finishGame("white")}else{$("whiteGuessBox").classList.add("hidden");$("continueBtn").classList.remove("hidden");$("eliminatedInfo").textContent="Mauvaise réponse : Mr White est éliminé. Le mot des Civils reste secret."}}
function evaluateWinner(){const alive=game.players.filter(p=>p.alive),civ=alive.filter(p=>p.role==="civil").length,under=alive.filter(p=>p.role==="under").length,white=alive.filter(p=>p.role==="white").length;if(under===0&&white===0)return"civil";if(under>0&&under>=civ+white)return"under";if(white>0&&white>=civ+under)return"white_survival";return null}
function continueAfterElimination(){const winner=evaluateWinner();if(winner){finishGame(winner);return}game.voteNumber++;selectedPlayerId=null;$("eliminateBtn").disabled=true;beginPlay()}
function finishGame(type){game.winner=type;const data={civil:["Victoire des Civils !","Tous les intrus ont été éliminés."],under:["Victoire des Undercover !","Ils sont désormais assez nombreux pour contrôler le vote."],white:["Victoire de Mr White !","Il a trouvé exactement le mot des Civils."],white_survival:["Victoire de Mr White !","Il a survécu jusqu’au duel final."]}[type];$("winnerTitle").textContent=data[0];$("winnerText").textContent=data[1];$("finalWords").innerHTML=`<div class="wordTile"><strong>Mot des Civils</strong><span>${escapeHtml(game.pair.civil)}</span></div><div class="wordTile"><strong>Mot des Undercover</strong><span>${escapeHtml(game.pair.undercover)}</span></div>`;showScreen("endScreen")}
document.querySelectorAll("[data-counter]").forEach(btn=>btn.addEventListener("click",()=>{const kind=btn.dataset.counter,dir=Number(btn.dataset.dir);if(kind==="players"){settings.players=clamp(settings.players+dir,4,20);settings.under=clamp(settings.under,1,Math.max(1,settings.players-3));settings.white=clamp(settings.white,0,Math.max(0,settings.players-settings.under-3))}else if(kind==="under"){settings.under=clamp(settings.under+dir,1,Math.max(1,settings.players-settings.white-3))}else{settings.white=clamp(settings.white+dir,0,Math.max(0,settings.players-settings.under-3))}updateSettingsUI()}));
$("forgotWordBtn").onclick=openRecallSelect;$("cancelRecallBtn").onclick=()=>showScreen("playScreen");$("backRecallSelectBtn").onclick=openRecallSelect;$("openRecallBtn").onclick=openRecallSecret;$("finishRecallBtn").onclick=finishRecall;
const holdRecallBtn=$("holdRecallBtn");
function bindRecallHold(){const start=e=>{if(e.cancelable)e.preventDefault();showRecallWord()};const end=e=>{if(e&&e.cancelable)e.preventDefault();hideRecallWord()};if("PointerEvent" in window){holdRecallBtn.addEventListener("pointerdown",e=>{start(e);try{holdRecallBtn.setPointerCapture(e.pointerId)}catch(err){}});["pointerup","pointercancel","lostpointercapture","pointerleave"].forEach(type=>holdRecallBtn.addEventListener(type,end))}else{holdRecallBtn.addEventListener("touchstart",start,{passive:false});["touchend","touchcancel"].forEach(type=>holdRecallBtn.addEventListener(type,end,{passive:false}));holdRecallBtn.addEventListener("mousedown",start);["mouseup","mouseleave"].forEach(type=>holdRecallBtn.addEventListener(type,end))}holdRecallBtn.addEventListener("contextmenu",e=>e.preventDefault())}
bindRecallHold();
document.addEventListener("visibilitychange",()=>{if(document.hidden)hideRecallWord()});window.addEventListener("pagehide",hideRecallWord);window.addEventListener("blur",hideRecallWord);window.addEventListener("orientationchange",()=>setTimeout(()=>window.scrollTo(0,0),180));
function detectPlatform(){const ua=navigator.userAgent||"";const isIOS=/iPad|iPhone|iPod/i.test(ua)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);const isAndroid=/Android/i.test(ua);if(isIOS)return{id:"ios",label:"iOS"};if(isAndroid)return{id:"android",label:"Android"};return{id:"web",label:"Web"}}
function applyPlatformLabel(){const platform=detectPlatform();document.documentElement.dataset.platform=platform.id;$("platformLabel").textContent=platform.label;document.title=`Undercover Party — ${platform.label}`}
function showStartError(message){const box=$("startError");box.textContent=message;box.classList.remove("hidden");try{box.scrollIntoView({block:"center"})}catch(err){}}
function clearStartError(){$("startError").classList.add("hidden");$("startError").textContent=""}
function safeStartNewGame(){clearStartError();try{startNewGame()}catch(err){console.error("Impossible de lancer la partie :",err);showStartError("La partie n’a pas pu démarrer. Ferme le clavier, puis réessaie. Si le problème persiste, recharge simplement la page.")}}
function bindReliableStartButton(){const button=$("startGameBtn");let lastTouch=0;let launching=false;const launch=e=>{if(e&&e.type==="touchend"){lastTouch=Date.now();if(e.cancelable)e.preventDefault()}else if(Date.now()-lastTouch<700){return}if(launching)return;launching=true;const active=document.activeElement;if(active&&/^(INPUT|SELECT|TEXTAREA)$/.test(active.tagName)){try{active.blur()}catch(err){}}requestAnimationFrame(()=>{safeStartNewGame();launching=false})};button.addEventListener("touchend",launch,{passive:false});button.addEventListener("click",launch);button.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();launch(e)}})}
$("newGameBtn").onclick=()=>{updateSettingsUI();showScreen("setupScreen")};$("backHomeBtn").onclick=()=>showScreen("homeScreen");$("categorySelect").onchange=e=>{settings.category=e.target.value;updatePoolStatus()};$("resetWordsBtn").onclick=()=>{safeStorage.removeItem(STORAGE_KEY);updatePoolStatus();$("resetWordsBtn").textContent="Historique réinitialisé ✓";setTimeout(()=>$("resetWordsBtn").textContent="Réinitialiser l’historique des mots",1400)};$("revealBtn").onclick=revealSecret;$("hideAndPassBtn").onclick=hideAndPass;$("eliminateBtn").onclick=eliminateSelected;$("checkWhiteGuessBtn").onclick=checkWhiteGuess;$("continueBtn").onclick=continueAfterElimination;$("samePlayersBtn").onclick=safeStartNewGame;$("resetBtn").onclick=()=>{updateSettingsUI();showScreen("setupScreen")};
applyPlatformLabel();bindReliableStartButton();updateSettingsUI();
if("serviceWorker" in navigator&&location.protocol.startsWith("http")){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
